### ISSUE TITLE
upgrade nebulous kubernetes clusters to 1.20

### ISSUE THREAD

**Issue by johndietz** [kubefirst/nebulous#15]
nebulous currently installs at a 1.17 which is almost end of life - this is the highest priority of the 1.5 release

**Comment by bil9000** [comment]
I'd like to work on this.

**Comment by johndietz** [comment]
thanks @bil9000, we actually discovered last night we'd prefer 1.20 in this next release, i'll adjust the title and consider this one claimed. appreciate your interest in contributing. 

It's sometimes as straightforward as just upgrading the eks module version - but there can be complications on apps with the upgrades, it's a bit of a discovery operation. let us know on this issue or in the kubefirst-community slack if you have any questions along the way!

https://github.com/kubefirst/nebulous/blob/main/gitops/terraform/base/eks/main.tf#L122

**Comment by bil9000** [comment]
Sounds great, happy to help!
