### ISSUE TITLE
init with terraform gitlab repo

### ISSUE THREAD

**Issue by johndietz** [kubefirst/nebulous#5]
# summary
the nebulous repo includes terraform iac that should be made available in the gitlab server on init.

# proposal
during the init process of the nebulous container execution, some terraform code is executed to provision the intro environment from a terraform directory in the nebulous repo. that very directory should be automatically uploaded to the private gitlab server during the setup process. this would allow for a very straightforward path to have automated source driven iac.

having the iac repo ready in turnkey fashion like that would allow for very low barrier of entry demo space for videos and tutorials.

# details

when running nebulous, the /terraform directory:
https://github.com/kubefirst/nebulous/tree/master/terraform
gets copied into the container at location `/terraform` as shown here
https://github.com/kubefirst/nebulous/blob/master/Dockerfile#L4

we want to add a new `terraform` git repository to the new gitlab server as part of the initialization process.

# questions

we currently code against the api
https://github.com/kubefirst/nebulous/blob/master/scripts/nebulous/init.sh#L166-L168

it might be more valuable to our open source users to establish a gitlab repo in terraform so they can manage repos as iac if they so choose.

terraform code would look like this
https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/group

**Comment by JaredEdwards** [comment]
In addition to the `terraform` repo we could add the `metaphor` repository to the gitlab server with terraform 
https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/project#import_url

I haven't taken this for a spin before but feel like if we can import the two directly from our `kubefirst` github it would be worth it

**Comment by johndietz** [comment]
this has been implemented with the nebulous 1.4 release
